version: '3.1'
services:
  postgres:
    image: postgres:14.5-alpine
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - ./pg:/data/postgres
    ports:
      - 5432:5432
  health_checker:
    build: .
    container_name: health_checker
    depends_on:
      - postgres
    ports:
        - "8080:8080"